Freemabd1/rw 114 edit annotation definition (#356)
* RW-114 implemented update of annotation definition and test cases.

* RW-114 added unique contraint for cohort_id and column_name.

* RW-114 changed property to columnName and added unique index for cohort_id and column_name.

* RW-114 created dao call to find annotation definition by cohortId and cohortAnnotationDefinitionId.

* Drop guava dep from build.gradle to fix GCS access (#357)

Without removal, I see the following when creating a new account (which attempts to read invite keys from GCS):

```
api_1                    | Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
api_1                    | 	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:77)
api_1                    | 	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:73)
api_1                    | 	at com.google.cloud.RetryHelper.run(RetryHelper.java:73)
api_1                    | 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
api_1                    | 	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:194)
api_1                    | 	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:186)
api_1                    | 	at org.pmiops.workbench.google.CloudStorageServiceImpl.readToString(CloudStorageServiceImpl.java:34)
api_1                    | 	at org.pmiops.workbench.google.CloudStorageServiceImpl.readInvitationKey(CloudStorageServiceImpl.java:21)
api_1                    | 	at org.pmiops.workbench.api.ProfileController.createAccount(ProfileController.java:262)
api_1                    | 	at org.pmiops.workbench.api.ProfileApiController.createAccount(ProfileApiController.java:41)
api_1                    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
api_1                    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
api_1                    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
api_1                    | 	at java.lang.reflect.Method.invoke(Method.java:498)
api_1                    | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
api_1                    | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
api_1                    | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
api_1                    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
api_1                    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
api_1                    | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
api_1                    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
```

Presumably something in here is having a bad interaction with app engine (or our particular set of deps).

This was added with cohort materialization, but I wasn't able to reproduce any issues after removal (something may come up later in this area).

* Johnstill/rw 265 8 participant detail (#360)

* No dimmer, no close on click outside for sidebars

* Push pagination buttons to bottom, tweak sidebar styles

* Remove unused import

* Review header

* Separate button groups

* RW-114 added extra checks for uniqueness.

* RW-114 added checks for uniqueness and a better error message when conflict occur.

* RW-114 implemented update of annotation definition and test cases.

* RW-114 added unique contraint for cohort_id and column_name.

* RW-114 changed property to columnName and added unique index for cohort_id and column_name.

* RW-114 created dao call to find annotation definition by cohortId and cohortAnnotationDefinitionId.

* RW-114 added extra checks for uniqueness.

* RW-114 added checks for uniqueness and a better error message when conflict occur.